### ISSUE TITLE
建议在创建的时候，显示详细的日志

### ISSUE THREAD

**Issue by find456789** [rekit/rekit-app#3]
因为网络的问题， 加载比较慢， 长时间卡在一个页面，  还以为出问题了，
如果能显示较为详细的日志，  让我知道还在加载 只是网络慢， 而不是程序挂了

谢谢

![image](https://user-images.githubusercontent.com/6580897/54861770-12df3180-4d6a-11e9-9e59-17611500ccc5.png)

**Comment by find456789** [comment]
创建项目这一步， 可以成功把  文件都建立好， 但是就没有下文了， 没有自动安装node_modules

于是我点了 取消，  然后用 这个app把刚才的项目， 导入进来， 发现 检测不到components， 其他似乎都正常

我手动 npm i 后， 可以正常启动， 就是在 app中，看不到 components



我尝试开了全局的ss， 似乎也是如此

**Comment by find456789** [comment]
![image](https://user-images.githubusercontent.com/6580897/54862185-d1528480-4d71-11e9-8e64-331c08e91881.png)

**Comment by find456789** [comment]
版本 3.0.0-beta.6 (3.0.0-beta.6)

![image](https://user-images.githubusercontent.com/6580897/54862194-e8917200-4d71-11e9-8acf-26a4437e94c9.png)

**Comment by find456789** [comment]
![image](https://user-images.githubusercontent.com/6580897/54862201-1676b680-4d72-11e9-8fa2-c03f6214095c.png)

**Comment by supnate** [comment]
postCreate.js 文件存在说明没创建完成。可以重试创建一个新项目，等待完成，不要点取消。
