### ISSUE TITLE
在mac上创建项目，运行诡异

### ISSUE THREAD

**Issue by find456789** [rekit/rekit-app#4]
最新版，

新建项目后

创建了本地文件夹， 然后从github 拉取了 rekit/boilerplate-rekit-react

并且我展开 文件夹 发现下载成功了， 接着，目录又自动消失了

**Comment by find456789** [comment]
无法新建项目， 点了新建， 他会创建文件夹，  下载了项目后， 它随后又删除了， 文件夹，

**Comment by supnate** [comment]
这应该是因为项目初始化失败，然后自动删除了项目，但是错误信息可能没有很好的反馈出来。
你可以使用命令行试一下：
```
npm install rekit@next -g
rekit create my-app
```

看看是否有错误显示。

**Comment by find456789** [comment]
![image](https://user-images.githubusercontent.com/6580897/56422611-e7088a80-62da-11e9-805a-f6261056d3f4.png)
