### ISSUE TITLE
make automatic upgrades an opt in

### ISSUE THREAD

**Issue by waveforms** [rekit/rekit-app#5]
Thanks for this project!
I was using 3.0.0-beta.23 and successfully created several projects. It worked great but then it auto updated to 3.0.0-beta.24. Now it does not work on my Mac Book (Mojave) it hangs on welcome screen.

Could you create a way to turn off auto-update?

I haven't reinstalled 3.0.0-beta.23 because it will probably just auto-update to 3.0.0-beta.24.

I tried to fully delete and re-install 3.0.0-beta.24 but it does not work. (Hangs on welcome screen)

I downloaded 3.0.0-beta.24 src and tried to run but it gives an error:
TypeError: Cannot read property 'ipcRenderer' of undefined
(anonymous function)
src/features/home/utils.js:72
  69 |   history.push('/plugins');
  70 | }
  71 | 
> 72 | window.bridge.ipcRenderer.on('open-project', (evt, dir) => openProject(dir));
  73 | window.bridge.ipcRenderer.on('redux-action', (evt, action) => store.getStore().dispatch(action));
  74 | window.bridge.ipcRenderer.on('new-project', evt => showNewProjectDialog());
  75 | window.bridge.ipcRenderer.on('show-welcome', evt => showWelcomePage());

**Comment by supnate** [comment]
Thank you very much for reporting this issue, I'm also using beta.24 it just works well, could you please check `~/.rekit/logs/rekit.log` to see if there's any exceptions? However I will publish a new beta asap.
Alternatively you can also start your project using command line:
```
> npm install -g rekit-studio@next
> cd your-prj
> rekit-studio -p 3000
```

**Comment by supnate** [comment]
Beta 25 just released which should fix this issue.

**Comment by waveforms** [comment]
Hey Nate! Thanks for your quick turnaround on my issue. It was a Holiday weekend here so I did not try  releases 25,26,27,28 or 29. I did try release 30 and it looks like everything works. I see you are now up to release 31, wow! I will try your newer releases soon.

**Comment by supnate** [comment]
No problem, since Rekit is in quick iteration for beta so I will keep it always auto updated. After it's formal release I will add an option for disable auto update.
